#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/sony/yoshino-common

PRODUCT_COPY_FILES += \
    vendor/sony/yoshino-common/proprietary/system/etc/permissions/privapp-permissions-qti.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/privapp-permissions-qti.xml \
    vendor/sony/yoshino-common/proprietary/system/etc/permissions/privapp-permissions-sony.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/privapp-permissions-sony.xml \
    vendor/sony/yoshino-common/proprietary/system/etc/sysconfig/qti_whitelist.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/sysconfig/qti_whitelist.xml \
    vendor/sony/yoshino-common/proprietary/system_ext/etc/dpm/dpm.conf:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/dpm/dpm.conf \
    vendor/sony/yoshino-common/proprietary/system_ext/etc/init/dpmd.rc:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/init/dpmd.rc \
    vendor/sony/yoshino-common/proprietary/system_ext/etc/permissions/com.qti.dpmframework.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.qti.dpmframework.xml \
    vendor/sony/yoshino-common/proprietary/system_ext/etc/permissions/dpmapi.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/dpmapi.xml \
    vendor/sony/yoshino-common/proprietary/system_ext/etc/permissions/qcrilhook.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/qcrilhook.xml \
    vendor/sony/yoshino-common/proprietary/system_ext/etc/permissions/qti_libpermissions.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/qti_libpermissions.xml \
    vendor/sony/yoshino-common/proprietary/system_ext/etc/permissions/qti_permissions.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/qti_permissions.xml \
    vendor/sony/yoshino-common/proprietary/system_ext/etc/permissions/telephony_system-ext_privapp-permissions-qti.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/telephony_system-ext_privapp-permissions-qti.xml \
    vendor/sony/yoshino-common/proprietary/vendor/camera/SOI20BS2/color_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/color_ctrl.dat \
    vendor/sony/yoshino-common/proprietary/vendor/camera/SOI20BS2/dataflow.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/dataflow.dat \
    vendor/sony/yoshino-common/proprietary/vendor/camera/SOI20BS2/exposure_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/exposure_ctrl.dat \
    vendor/sony/yoshino-common/proprietary/vendor/camera/SOI20BS2/exposure_ctrl_diagram.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/exposure_ctrl_diagram.dat \
    vendor/sony/yoshino-common/proprietary/vendor/camera/SOI20BS2/exposure_ctrl_gamma.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/exposure_ctrl_gamma.dat \
    vendor/sony/yoshino-common/proprietary/vendor/camera/SOI20BS2/face_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/face_detector.dat \
    vendor/sony/yoshino-common/proprietary/vendor/camera/SOI20BS2/flicker_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/flicker_detector.dat \
    vendor/sony/yoshino-common/proprietary/vendor/camera/SOI20BS2/focus_stats_conv.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/focus_stats_conv.dat \
    vendor/sony/yoshino-common/proprietary/vendor/camera/SOI20BS2/food_comp_yummy.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/food_comp_yummy.dat \
    vendor/sony/yoshino-common/proprietary/vendor/camera/SOI20BS2/food_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/food_detector.dat \
    vendor/sony/yoshino-common/proprietary/vendor/camera/SOI20BS2/hal_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/hal_ctrl.dat \
    vendor/sony/yoshino-common/proprietary/vendor/camera/SOI20BS2/hal_ctrl_platform_abf.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/hal_ctrl_platform_abf.dat \
    vendor/sony/yoshino-common/proprietary/vendor/camera/SOI20BS2/hal_ctrl_platform_asf_lin.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/hal_ctrl_platform_asf_lin.dat \
    vendor/sony/yoshino-common/proprietary/vendor/camera/SOI20BS2/hal_ctrl_platform_asf_stp.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/hal_ctrl_platform_asf_stp.dat \
    vendor/sony/yoshino-common/proprietary/vendor/camera/SOI20BS2/hal_ctrl_platform_eccc.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/hal_ctrl_platform_eccc.dat \
    vendor/sony/yoshino-common/proprietary/vendor/camera/SOI20BS2/hal_ctrl_platform_gic.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/hal_ctrl_platform_gic.dat \
    vendor/sony/yoshino-common/proprietary/vendor/camera/SOI20BS2/hal_ctrl_platform_ltm.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/hal_ctrl_platform_ltm.dat \
    vendor/sony/yoshino-common/proprietary/vendor/camera/SOI20BS2/hal_ctrl_platform_nree.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/hal_ctrl_platform_nree.dat \
    vendor/sony/yoshino-common/proprietary/vendor/camera/SOI20BS2/hdr_comp.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/hdr_comp.dat \
    vendor/sony/yoshino-common/proprietary/vendor/camera/SOI20BS2/idt_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/idt_ctrl.dat \
    vendor/sony/yoshino-common/proprietary/vendor/camera/SOI20BS2/image_conv.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/image_conv.dat \
    vendor/sony/yoshino-common/proprietary/vendor/camera/SOI20BS2/image_conv_canele.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/image_conv_canele.dat \
    vendor/sony/yoshino-common/proprietary/vendor/camera/SOI20BS2/image_conv_cheesescone.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/image_conv_cheesescone.dat \
    vendor/sony/yoshino-common/proprietary/vendor/camera/SOI20BS2/image_conv_dars.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/image_conv_dars.dat \
    vendor/sony/yoshino-common/proprietary/vendor/camera/SOI20BS2/image_conv_marble.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/image_conv_marble.dat \
    vendor/sony/yoshino-common/proprietary/vendor/camera/SOI20BS2/image_conv_raisin.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/image_conv_raisin.dat \
    vendor/sony/yoshino-common/proprietary/vendor/camera/SOI20BS2/image_conv_spica.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/image_conv_spica.dat \
    vendor/sony/yoshino-common/proprietary/vendor/camera/SOI20BS2/lens_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/lens_ctrl.dat \
    vendor/sony/yoshino-common/proprietary/vendor/camera/SOI20BS2/motion_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/motion_detector.dat \
    vendor/sony/yoshino-common/proprietary/vendor/camera/SOI20BS2/motion_detector_sumomo.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/motion_detector_sumomo.dat \
    vendor/sony/yoshino-common/proprietary/vendor/camera/SOI20BS2/motion_estimation.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/motion_estimation.dat \
    vendor/sony/yoshino-common/proprietary/vendor/camera/SOI20BS2/multiframe_nr.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/multiframe_nr.dat \
    vendor/sony/yoshino-common/proprietary/vendor/camera/SOI20BS2/multiframe_nr_melonpan.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/multiframe_nr_melonpan.dat \
    vendor/sony/yoshino-common/proprietary/vendor/camera/SOI20BS2/multiframe_nr_mugichoco.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/multiframe_nr_mugichoco.dat \
    vendor/sony/yoshino-common/proprietary/vendor/camera/SOI20BS2/multiframe_nr_toppo.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/multiframe_nr_toppo.dat \
    vendor/sony/yoshino-common/proprietary/vendor/camera/SOI20BS2/object_tracker.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/object_tracker.dat \
    vendor/sony/yoshino-common/proprietary/vendor/camera/SOI20BS2/prc_image_conv.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/prc_image_conv.dat \
    vendor/sony/yoshino-common/proprietary/vendor/camera/SOI20BS2/scene_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/scene_detector.dat \
    vendor/sony/yoshino-common/proprietary/vendor/camera/SOI20BS2_BU64747GWZ_XCF.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2_BU64747GWZ_XCF.dat \
    vendor/sony/yoshino-common/proprietary/vendor/camera/SOI20BS2_BU64747GWZ_XFW.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2_BU64747GWZ_XFW.dat \
    vendor/sony/yoshino-common/proprietary/vendor/camera/default.dat:$(TARGET_COPY_OUT_VENDOR)/camera/default.dat \
    vendor/sony/yoshino-common/proprietary/vendor/camera/flash.dat:$(TARGET_COPY_OUT_VENDOR)/camera/flash.dat \
    vendor/sony/yoshino-common/proprietary/vendor/camera/snapshot.dat:$(TARGET_COPY_OUT_VENDOR)/camera/snapshot.dat \
    vendor/sony/yoshino-common/proprietary/vendor/camera/streaming.dat:$(TARGET_COPY_OUT_VENDOR)/camera/streaming.dat \
    vendor/sony/yoshino-common/proprietary/vendor/camera/supported.dat:$(TARGET_COPY_OUT_VENDOR)/camera/supported.dat \
    vendor/sony/yoshino-common/proprietary/vendor/camera/version.dat:$(TARGET_COPY_OUT_VENDOR)/camera/version.dat \
    vendor/sony/yoshino-common/proprietary/vendor/etc/acdbdata/Sony/Sony_yoshino_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Sony/Sony_yoshino_Bluetooth_cal.acdb \
    vendor/sony/yoshino-common/proprietary/vendor/etc/acdbdata/Sony/Sony_yoshino_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Sony/Sony_yoshino_General_cal.acdb \
    vendor/sony/yoshino-common/proprietary/vendor/etc/acdbdata/Sony/Sony_yoshino_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Sony/Sony_yoshino_Global_cal.acdb \
    vendor/sony/yoshino-common/proprietary/vendor/etc/acdbdata/Sony/Sony_yoshino_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Sony/Sony_yoshino_Handset_cal.acdb \
    vendor/sony/yoshino-common/proprietary/vendor/etc/acdbdata/Sony/Sony_yoshino_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Sony/Sony_yoshino_Hdmi_cal.acdb \
    vendor/sony/yoshino-common/proprietary/vendor/etc/acdbdata/Sony/Sony_yoshino_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Sony/Sony_yoshino_Headset_cal.acdb \
    vendor/sony/yoshino-common/proprietary/vendor/etc/acdbdata/Sony/Sony_yoshino_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Sony/Sony_yoshino_Speaker_cal.acdb \
    vendor/sony/yoshino-common/proprietary/vendor/etc/acdbdata/Sony/workspaceFile_Sony_yoshino.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Sony/workspaceFile_Sony_yoshino.qwsp \
    vendor/sony/yoshino-common/proprietary/vendor/etc/apdr.conf:$(TARGET_COPY_OUT_VENDOR)/etc/apdr.conf \
    vendor/sony/yoshino-common/proprietary/vendor/etc/audio_tuning_mixer.txt:$(TARGET_COPY_OUT_VENDOR)/etc/audio_tuning_mixer.txt \
    vendor/sony/yoshino-common/proprietary/vendor/etc/cne/mwqem.conf:$(TARGET_COPY_OUT_VENDOR)/etc/cne/mwqem.conf \
    vendor/sony/yoshino-common/proprietary/vendor/etc/cne/profileMwqem.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/profileMwqem.xml \
    vendor/sony/yoshino-common/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile1.xml \
    vendor/sony/yoshino-common/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile2.xml \
    vendor/sony/yoshino-common/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile3.xml \
    vendor/sony/yoshino-common/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile4.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile4.xml \
    vendor/sony/yoshino-common/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile5.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile5.xml \
    vendor/sony/yoshino-common/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile6.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile6.xml \
    vendor/sony/yoshino-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile1.xml \
    vendor/sony/yoshino-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile15.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile15.xml \
    vendor/sony/yoshino-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile16.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile16.xml \
    vendor/sony/yoshino-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile17.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile17.xml \
    vendor/sony/yoshino-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile18.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile18.xml \
    vendor/sony/yoshino-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile19.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile19.xml \
    vendor/sony/yoshino-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile2.xml \
    vendor/sony/yoshino-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile20.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile20.xml \
    vendor/sony/yoshino-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile21.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile21.xml \
    vendor/sony/yoshino-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile3.xml \
    vendor/sony/yoshino-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile32.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile32.xml \
    vendor/sony/yoshino-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile4.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile4.xml \
    vendor/sony/yoshino-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile5.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile5.xml \
    vendor/sony/yoshino-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile6.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile6.xml \
    vendor/sony/yoshino-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile7.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile7.xml \
    vendor/sony/yoshino-common/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile1.xml \
    vendor/sony/yoshino-common/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile2.xml \
    vendor/sony/yoshino-common/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile3.xml \
    vendor/sony/yoshino-common/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile4.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile4.xml \
    vendor/sony/yoshino-common/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile5.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile5.xml \
    vendor/sony/yoshino-common/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile6.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile6.xml \
    vendor/sony/yoshino-common/proprietary/vendor/etc/data/dsi_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/data/dsi_config.xml \
    vendor/sony/yoshino-common/proprietary/vendor/etc/data/netmgr_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/data/netmgr_config.xml \
    vendor/sony/yoshino-common/proprietary/vendor/etc/firmware/cmnlib.b00:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/cmnlib.b00 \
    vendor/sony/yoshino-common/proprietary/vendor/etc/firmware/cmnlib.b01:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/cmnlib.b01 \
    vendor/sony/yoshino-common/proprietary/vendor/etc/firmware/cmnlib.b02:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/cmnlib.b02 \
    vendor/sony/yoshino-common/proprietary/vendor/etc/firmware/cmnlib.b03:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/cmnlib.b03 \
    vendor/sony/yoshino-common/proprietary/vendor/etc/firmware/cmnlib.b04:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/cmnlib.b04 \
    vendor/sony/yoshino-common/proprietary/vendor/etc/firmware/cmnlib.b05:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/cmnlib.b05 \
    vendor/sony/yoshino-common/proprietary/vendor/etc/firmware/cmnlib.b06:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/cmnlib.b06 \
    vendor/sony/yoshino-common/proprietary/vendor/etc/firmware/cmnlib.mdt:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/cmnlib.mdt \
    vendor/sony/yoshino-common/proprietary/vendor/etc/firmware/cmnlib64.b00:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/cmnlib64.b00 \
    vendor/sony/yoshino-common/proprietary/vendor/etc/firmware/cmnlib64.b01:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/cmnlib64.b01 \
    vendor/sony/yoshino-common/proprietary/vendor/etc/firmware/cmnlib64.b02:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/cmnlib64.b02 \
    vendor/sony/yoshino-common/proprietary/vendor/etc/firmware/cmnlib64.b03:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/cmnlib64.b03 \
    vendor/sony/yoshino-common/proprietary/vendor/etc/firmware/cmnlib64.b04:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/cmnlib64.b04 \
    vendor/sony/yoshino-common/proprietary/vendor/etc/firmware/cmnlib64.b05:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/cmnlib64.b05 \
    vendor/sony/yoshino-common/proprietary/vendor/etc/firmware/cmnlib64.b06:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/cmnlib64.b06 \
    vendor/sony/yoshino-common/proprietary/vendor/etc/firmware/cmnlib64.mdt:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/cmnlib64.mdt \
    vendor/sony/yoshino-common/proprietary/vendor/etc/firmware/fidocfg.b00:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fidocfg.b00 \
    vendor/sony/yoshino-common/proprietary/vendor/etc/firmware/fidocfg.b01:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fidocfg.b01 \
    vendor/sony/yoshino-common/proprietary/vendor/etc/firmware/fidocfg.b02:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fidocfg.b02 \
    vendor/sony/yoshino-common/proprietary/vendor/etc/firmware/fidocfg.b03:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fidocfg.b03 \
    vendor/sony/yoshino-common/proprietary/vendor/etc/firmware/fidocfg.b04:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fidocfg.b04 \
    vendor/sony/yoshino-common/proprietary/vendor/etc/firmware/fidocfg.b05:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fidocfg.b05 \
    vendor/sony/yoshino-common/proprietary/vendor/etc/firmware/fidocfg.b06:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fidocfg.b06 \
    vendor/sony/yoshino-common/proprietary/vendor/etc/firmware/fidocfg.b07:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fidocfg.b07 \
    vendor/sony/yoshino-common/proprietary/vendor/etc/firmware/fidocfg.mdt:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fidocfg.mdt \
    vendor/sony/yoshino-common/proprietary/vendor/etc/firmware/fidocrypto.b00:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fidocrypto.b00 \
    vendor/sony/yoshino-common/proprietary/vendor/etc/firmware/fidocrypto.b01:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fidocrypto.b01 \
    vendor/sony/yoshino-common/proprietary/vendor/etc/firmware/fidocrypto.b02:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fidocrypto.b02 \
    vendor/sony/yoshino-common/proprietary/vendor/etc/firmware/fidocrypto.b03:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fidocrypto.b03 \
    vendor/sony/yoshino-common/proprietary/vendor/etc/firmware/fidocrypto.b04:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fidocrypto.b04 \
    vendor/sony/yoshino-common/proprietary/vendor/etc/firmware/fidocrypto.b05:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fidocrypto.b05 \
    vendor/sony/yoshino-common/proprietary/vendor/etc/firmware/fidocrypto.b06:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fidocrypto.b06 \
    vendor/sony/yoshino-common/proprietary/vendor/etc/firmware/fidocrypto.b07:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fidocrypto.b07 \
    vendor/sony/yoshino-common/proprietary/vendor/etc/firmware/fidocrypto.mdt:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fidocrypto.mdt \
    vendor/sony/yoshino-common/proprietary/vendor/etc/firmware/tzattest.b00:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/tzattest.b00 \
    vendor/sony/yoshino-common/proprietary/vendor/etc/firmware/tzattest.b01:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/tzattest.b01 \
    vendor/sony/yoshino-common/proprietary/vendor/etc/firmware/tzattest.b02:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/tzattest.b02 \
    vendor/sony/yoshino-common/proprietary/vendor/etc/firmware/tzattest.b03:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/tzattest.b03 \
    vendor/sony/yoshino-common/proprietary/vendor/etc/firmware/tzattest.b04:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/tzattest.b04 \
    vendor/sony/yoshino-common/proprietary/vendor/etc/firmware/tzattest.b05:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/tzattest.b05 \
    vendor/sony/yoshino-common/proprietary/vendor/etc/firmware/tzattest.b06:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/tzattest.b06 \
    vendor/sony/yoshino-common/proprietary/vendor/etc/firmware/tzattest.b07:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/tzattest.b07 \
    vendor/sony/yoshino-common/proprietary/vendor/etc/firmware/tzattest.mdt:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/tzattest.mdt \
    vendor/sony/yoshino-common/proprietary/vendor/etc/firmware/tzsuntory.b00:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/tzsuntory.b00 \
    vendor/sony/yoshino-common/proprietary/vendor/etc/firmware/tzsuntory.b01:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/tzsuntory.b01 \
    vendor/sony/yoshino-common/proprietary/vendor/etc/firmware/tzsuntory.b02:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/tzsuntory.b02 \
    vendor/sony/yoshino-common/proprietary/vendor/etc/firmware/tzsuntory.b03:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/tzsuntory.b03 \
    vendor/sony/yoshino-common/proprietary/vendor/etc/firmware/tzsuntory.b04:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/tzsuntory.b04 \
    vendor/sony/yoshino-common/proprietary/vendor/etc/firmware/tzsuntory.b05:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/tzsuntory.b05 \
    vendor/sony/yoshino-common/proprietary/vendor/etc/firmware/tzsuntory.b06:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/tzsuntory.b06 \
    vendor/sony/yoshino-common/proprietary/vendor/etc/firmware/tzsuntory.b07:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/tzsuntory.b07 \
    vendor/sony/yoshino-common/proprietary/vendor/etc/firmware/tzsuntory.mdt:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/tzsuntory.mdt \
    vendor/sony/yoshino-common/proprietary/vendor/etc/firmware/tztpm.b00:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/tztpm.b00 \
    vendor/sony/yoshino-common/proprietary/vendor/etc/firmware/tztpm.b01:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/tztpm.b01 \
    vendor/sony/yoshino-common/proprietary/vendor/etc/firmware/tztpm.b02:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/tztpm.b02 \
    vendor/sony/yoshino-common/proprietary/vendor/etc/firmware/tztpm.b03:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/tztpm.b03 \
    vendor/sony/yoshino-common/proprietary/vendor/etc/firmware/tztpm.b04:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/tztpm.b04 \
    vendor/sony/yoshino-common/proprietary/vendor/etc/firmware/tztpm.b05:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/tztpm.b05 \
    vendor/sony/yoshino-common/proprietary/vendor/etc/firmware/tztpm.b06:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/tztpm.b06 \
    vendor/sony/yoshino-common/proprietary/vendor/etc/firmware/tztpm.b07:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/tztpm.b07 \
    vendor/sony/yoshino-common/proprietary/vendor/etc/firmware/tztpm.mdt:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/tztpm.mdt \
    vendor/sony/yoshino-common/proprietary/vendor/etc/flashled_calc_parameters.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/flashled_calc_parameters.cfg \
    vendor/sony/yoshino-common/proprietary/vendor/etc/flp.conf:$(TARGET_COPY_OUT_VENDOR)/etc/flp.conf \
    vendor/sony/yoshino-common/proprietary/vendor/etc/gps.conf:$(TARGET_COPY_OUT_VENDOR)/etc/gps.conf \
    vendor/sony/yoshino-common/proprietary/vendor/etc/idd.conf:$(TARGET_COPY_OUT_VENDOR)/etc/idd.conf \
    vendor/sony/yoshino-common/proprietary/vendor/etc/idd.fstab:$(TARGET_COPY_OUT_VENDOR)/etc/idd.fstab \
    vendor/sony/yoshino-common/proprietary/vendor/etc/iddd.conf:$(TARGET_COPY_OUT_VENDOR)/etc/iddd.conf \
    vendor/sony/yoshino-common/proprietary/vendor/etc/init/android.hardware.bluetooth@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.bluetooth@1.0-service-qti.rc \
    vendor/sony/yoshino-common/proprietary/vendor/etc/init/android.hardware.drm@1.1-service.widevine.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm@1.1-service.widevine.rc \
    vendor/sony/yoshino-common/proprietary/vendor/etc/init/android.hardware.gatekeeper@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gatekeeper@1.0-service-qti.rc \
    vendor/sony/yoshino-common/proprietary/vendor/etc/init/android.hardware.gnss@2.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gnss@2.0-service-qti.rc \
    vendor/sony/yoshino-common/proprietary/vendor/etc/init/android.hardware.keymaster@3.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.keymaster@3.0-service-qti.rc \
    vendor/sony/yoshino-common/proprietary/vendor/etc/init/cnd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/cnd.rc \
    vendor/sony/yoshino-common/proprietary/vendor/etc/init/dataadpl.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dataadpl.rc \
    vendor/sony/yoshino-common/proprietary/vendor/etc/init/dataqti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dataqti.rc \
    vendor/sony/yoshino-common/proprietary/vendor/etc/init/dpmQmiMgr.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dpmQmiMgr.rc \
    vendor/sony/yoshino-common/proprietary/vendor/etc/init/fpc_fingerprint@2.1_HIDL-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/fpc_fingerprint@2.1_HIDL-service.rc \
    vendor/sony/yoshino-common/proprietary/vendor/etc/init/ims_rtp_daemon_legacy.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/ims_rtp_daemon_legacy.rc \
    vendor/sony/yoshino-common/proprietary/vendor/etc/init/imsdatadaemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/imsdatadaemon.rc \
    vendor/sony/yoshino-common/proprietary/vendor/etc/init/imsqmidaemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/imsqmidaemon.rc \
    vendor/sony/yoshino-common/proprietary/vendor/etc/init/imsrcsd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/imsrcsd.rc \
    vendor/sony/yoshino-common/proprietary/vendor/etc/init/init.keyprovd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.keyprovd.rc \
    vendor/sony/yoshino-common/proprietary/vendor/etc/init/init.sony.idd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.sony.idd.rc \
    vendor/sony/yoshino-common/proprietary/vendor/etc/init/init.taqmi.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.taqmi.rc \
    vendor/sony/yoshino-common/proprietary/vendor/etc/init/init.time_daemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.time_daemon.rc \
    vendor/sony/yoshino-common/proprietary/vendor/etc/init/mlog_qmi_service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/mlog_qmi_service.rc \
    vendor/sony/yoshino-common/proprietary/vendor/etc/init/netmgrd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/netmgrd.rc \
    vendor/sony/yoshino-common/proprietary/vendor/etc/init/port-bridge.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/port-bridge.rc \
    vendor/sony/yoshino-common/proprietary/vendor/etc/init/qcrild.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qcrild.rc \
    vendor/sony/yoshino-common/proprietary/vendor/etc/init/sct_service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/sct_service.rc \
    vendor/sony/yoshino-common/proprietary/vendor/etc/init/vendor.display.color@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.display.color@1.0-service.rc \
    vendor/sony/yoshino-common/proprietary/vendor/etc/init/vendor.qti.hardware.qteeconnector@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.qteeconnector@1.0-service.rc \
    vendor/sony/yoshino-common/proprietary/vendor/etc/init/vendor.qti.hardware.tui_comm@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.tui_comm@1.0-service-qti.rc \
    vendor/sony/yoshino-common/proprietary/vendor/etc/init/vendor.qti.rmt_storage.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.rmt_storage.rc \
    vendor/sony/yoshino-common/proprietary/vendor/etc/init/vendor.qti.tftp.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.tftp.rc \
    vendor/sony/yoshino-common/proprietary/vendor/etc/init/vendor.semc.hardware.secd@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.semc.hardware.secd@1.0-service.rc \
    vendor/sony/yoshino-common/proprietary/vendor/etc/init/vendor.semc.system.idd@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.semc.system.idd@1.0-service.rc \
    vendor/sony/yoshino-common/proprietary/vendor/etc/init/vendor.somc.hardware.camera.provider@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.somc.hardware.camera.provider@1.0-service.rc \
    vendor/sony/yoshino-common/proprietary/vendor/etc/init/vendor.somc.hardware.miscta@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.somc.hardware.miscta@1.0-service.rc \
    vendor/sony/yoshino-common/proprietary/vendor/etc/izat.conf:$(TARGET_COPY_OUT_VENDOR)/etc/izat.conf \
    vendor/sony/yoshino-common/proprietary/vendor/etc/media_codecs_vendor.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_vendor.xml \
    vendor/sony/yoshino-common/proprietary/vendor/etc/media_profiles_V1_0.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_profiles_V1_0.xml \
    vendor/sony/yoshino-common/proprietary/vendor/etc/msm_irqbalance.conf:$(TARGET_COPY_OUT_VENDOR)/etc/msm_irqbalance.conf \
    vendor/sony/yoshino-common/proprietary/vendor/etc/public.libraries-sony.txt:$(TARGET_COPY_OUT_VENDOR)/etc/public.libraries-sony.txt \
    vendor/sony/yoshino-common/proprietary/vendor/etc/public.libraries.txt:$(TARGET_COPY_OUT_VENDOR)/etc/public.libraries.txt \
    vendor/sony/yoshino-common/proprietary/vendor/etc/qns.fstab:$(TARGET_COPY_OUT_VENDOR)/etc/qns.fstab \
    vendor/sony/yoshino-common/proprietary/vendor/etc/sap.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sap.conf \
    vendor/sony/yoshino-common/proprietary/vendor/etc/sec_config:$(TARGET_COPY_OUT_VENDOR)/etc/sec_config \
    vendor/sony/yoshino-common/proprietary/vendor/etc/seccomp_policy/imsrtp.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/imsrtp.policy \
    vendor/sony/yoshino-common/proprietary/vendor/etc/seccomp_policy/mediacodec.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/mediacodec.policy \
    vendor/sony/yoshino-common/proprietary/vendor/etc/seccomp_policy/mediaextractor.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/mediaextractor.policy \
    vendor/sony/yoshino-common/proprietary/vendor/etc/security/idd_config.pem:$(TARGET_COPY_OUT_VENDOR)/etc/security/idd_config.pem \
    vendor/sony/yoshino-common/proprietary/vendor/etc/security/idd_report.pem:$(TARGET_COPY_OUT_VENDOR)/etc/security/idd_report.pem \
    vendor/sony/yoshino-common/proprietary/vendor/etc/sensors/hals.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/hals.conf \
    vendor/sony/yoshino-common/proprietary/vendor/etc/sensors/sensor_def_qcomdev.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/sensor_def_qcomdev.conf \
    vendor/sony/yoshino-common/proprietary/vendor/etc/sensors/sensor_def_somc_platform.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/sensor_def_somc_platform.conf \
    vendor/sony/yoshino-common/proprietary/vendor/etc/sony_effect/znr_param_44k_MainCam.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/sony_effect/znr_param_44k_MainCam.tbl \
    vendor/sony/yoshino-common/proprietary/vendor/etc/sony_effect/znr_param_44k_MainSubSemCam.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/sony_effect/znr_param_44k_MainSubSemCam.tbl \
    vendor/sony/yoshino-common/proprietary/vendor/etc/sony_effect/znr_param_44k_MainSubSoiCam.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/sony_effect/znr_param_44k_MainSubSoiCam.tbl \
    vendor/sony/yoshino-common/proprietary/vendor/etc/sony_effect/znr_param_44k_NoCam.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/sony_effect/znr_param_44k_NoCam.tbl \
    vendor/sony/yoshino-common/proprietary/vendor/etc/sony_effect/znr_param_44k_SubSemCam.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/sony_effect/znr_param_44k_SubSemCam.tbl \
    vendor/sony/yoshino-common/proprietary/vendor/etc/sony_effect/znr_param_44k_SubSoiCam.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/sony_effect/znr_param_44k_SubSoiCam.tbl \
    vendor/sony/yoshino-common/proprietary/vendor/etc/sony_effect/znr_param_48k_MainCam.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/sony_effect/znr_param_48k_MainCam.tbl \
    vendor/sony/yoshino-common/proprietary/vendor/etc/sony_effect/znr_param_48k_MainSubSemCam.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/sony_effect/znr_param_48k_MainSubSemCam.tbl \
    vendor/sony/yoshino-common/proprietary/vendor/etc/sony_effect/znr_param_48k_MainSubSoiCam.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/sony_effect/znr_param_48k_MainSubSoiCam.tbl \
    vendor/sony/yoshino-common/proprietary/vendor/etc/sony_effect/znr_param_48k_NoCam.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/sony_effect/znr_param_48k_NoCam.tbl \
    vendor/sony/yoshino-common/proprietary/vendor/etc/sony_effect/znr_param_48k_SubSemCam.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/sony_effect/znr_param_48k_SubSemCam.tbl \
    vendor/sony/yoshino-common/proprietary/vendor/etc/sony_effect/znr_param_48k_SubSoiCam.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/sony_effect/znr_param_48k_SubSoiCam.tbl \
    vendor/sony/yoshino-common/proprietary/vendor/etc/sound_trigger_mixer_paths.xml:$(TARGET_COPY_OUT_VENDOR)/etc/sound_trigger_mixer_paths.xml \
    vendor/sony/yoshino-common/proprietary/vendor/etc/sound_trigger_platform_info.xml:$(TARGET_COPY_OUT_VENDOR)/etc/sound_trigger_platform_info.xml \
    vendor/sony/yoshino-common/proprietary/vendor/etc/wifi/p2p_supplicant_overlay.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/p2p_supplicant_overlay.conf \
    vendor/sony/yoshino-common/proprietary/vendor/firmware/a530_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_pfp.fw \
    vendor/sony/yoshino-common/proprietary/vendor/firmware/a530_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_pm4.fw \
    vendor/sony/yoshino-common/proprietary/vendor/firmware/a540_gpmu.fw2:$(TARGET_COPY_OUT_VENDOR)/firmware/a540_gpmu.fw2 \
    vendor/sony/yoshino-common/proprietary/vendor/firmware/a540_zap.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/a540_zap.b00 \
    vendor/sony/yoshino-common/proprietary/vendor/firmware/a540_zap.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/a540_zap.b01 \
    vendor/sony/yoshino-common/proprietary/vendor/firmware/a540_zap.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/a540_zap.b02 \
    vendor/sony/yoshino-common/proprietary/vendor/firmware/a540_zap.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/a540_zap.elf \
    vendor/sony/yoshino-common/proprietary/vendor/firmware/a540_zap.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/a540_zap.mdt \
    vendor/sony/yoshino-common/proprietary/vendor/firmware/cpp_firmware_v1_10_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_10_0.fw \
    vendor/sony/yoshino-common/proprietary/vendor/firmware/cpp_firmware_v1_12_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_12_0.fw \
    vendor/sony/yoshino-common/proprietary/vendor/firmware/cpp_firmware_v1_1_1.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_1_1.fw \
    vendor/sony/yoshino-common/proprietary/vendor/firmware/cpp_firmware_v1_1_6.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_1_6.fw \
    vendor/sony/yoshino-common/proprietary/vendor/firmware/cpp_firmware_v1_2_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_2_0.fw \
    vendor/sony/yoshino-common/proprietary/vendor/firmware/cpp_firmware_v1_4_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_4_0.fw \
    vendor/sony/yoshino-common/proprietary/vendor/firmware/cpp_firmware_v1_5_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_0.fw \
    vendor/sony/yoshino-common/proprietary/vendor/firmware/cpp_firmware_v1_5_1.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_1.fw \
    vendor/sony/yoshino-common/proprietary/vendor/firmware/cpp_firmware_v1_5_2.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_2.fw \
    vendor/sony/yoshino-common/proprietary/vendor/firmware/cpp_firmware_v1_6_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_6_0.fw \
    vendor/sony/yoshino-common/proprietary/vendor/firmware/cpp_firmware_v1_8_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_8_0.fw \
    vendor/sony/yoshino-common/proprietary/vendor/firmware/ipa_fws.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b00 \
    vendor/sony/yoshino-common/proprietary/vendor/firmware/ipa_fws.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b01 \
    vendor/sony/yoshino-common/proprietary/vendor/firmware/ipa_fws.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b02 \
    vendor/sony/yoshino-common/proprietary/vendor/firmware/ipa_fws.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b03 \
    vendor/sony/yoshino-common/proprietary/vendor/firmware/ipa_fws.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b04 \
    vendor/sony/yoshino-common/proprietary/vendor/firmware/ipa_fws.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.elf \
    vendor/sony/yoshino-common/proprietary/vendor/firmware/ipa_fws.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.mdt \
    vendor/sony/yoshino-common/proprietary/vendor/firmware/tzfingerprint.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/tzfingerprint.b00 \
    vendor/sony/yoshino-common/proprietary/vendor/firmware/tzfingerprint.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/tzfingerprint.b02 \
    vendor/sony/yoshino-common/proprietary/vendor/firmware/tzfingerprint.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/tzfingerprint.b03 \
    vendor/sony/yoshino-common/proprietary/vendor/firmware/tzfingerprint.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/tzfingerprint.b04 \
    vendor/sony/yoshino-common/proprietary/vendor/firmware/tzfingerprint.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/tzfingerprint.b05 \
    vendor/sony/yoshino-common/proprietary/vendor/firmware/tzfingerprint.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/tzfingerprint.b06 \
    vendor/sony/yoshino-common/proprietary/vendor/firmware/tzfingerprint.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/tzfingerprint.b07 \
    vendor/sony/yoshino-common/proprietary/vendor/firmware/tzhdcp.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/tzhdcp.b00 \
    vendor/sony/yoshino-common/proprietary/vendor/firmware/tzhdcp.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/tzhdcp.b01 \
    vendor/sony/yoshino-common/proprietary/vendor/firmware/tzhdcp.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/tzhdcp.b02 \
    vendor/sony/yoshino-common/proprietary/vendor/firmware/tzhdcp.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/tzhdcp.b03 \
    vendor/sony/yoshino-common/proprietary/vendor/firmware/tzhdcp.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/tzhdcp.b04 \
    vendor/sony/yoshino-common/proprietary/vendor/firmware/tzhdcp.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/tzhdcp.b05 \
    vendor/sony/yoshino-common/proprietary/vendor/firmware/tzhdcp.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/tzhdcp.b06 \
    vendor/sony/yoshino-common/proprietary/vendor/firmware/tzhdcp.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/tzhdcp.b07 \
    vendor/sony/yoshino-common/proprietary/vendor/firmware/tzhdcp.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/tzhdcp.mdt \
    vendor/sony/yoshino-common/proprietary/vendor/firmware/tzwidevine.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/tzwidevine.b00 \
    vendor/sony/yoshino-common/proprietary/vendor/firmware/tzwidevine.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/tzwidevine.b01 \
    vendor/sony/yoshino-common/proprietary/vendor/firmware/tzwidevine.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/tzwidevine.b02 \
    vendor/sony/yoshino-common/proprietary/vendor/firmware/tzwidevine.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/tzwidevine.b03 \
    vendor/sony/yoshino-common/proprietary/vendor/firmware/tzwidevine.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/tzwidevine.b04 \
    vendor/sony/yoshino-common/proprietary/vendor/firmware/tzwidevine.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/tzwidevine.b05 \
    vendor/sony/yoshino-common/proprietary/vendor/firmware/tzwidevine.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/tzwidevine.b06 \
    vendor/sony/yoshino-common/proprietary/vendor/firmware/tzwidevine.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/tzwidevine.b07 \
    vendor/sony/yoshino-common/proprietary/vendor/firmware/tzwidevine.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/tzwidevine.mdt \
    vendor/sony/yoshino-common/proprietary/vendor/firmware/tzwvcpybuf.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/tzwvcpybuf.b00 \
    vendor/sony/yoshino-common/proprietary/vendor/firmware/tzwvcpybuf.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/tzwvcpybuf.b01 \
    vendor/sony/yoshino-common/proprietary/vendor/firmware/tzwvcpybuf.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/tzwvcpybuf.b02 \
    vendor/sony/yoshino-common/proprietary/vendor/firmware/tzwvcpybuf.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/tzwvcpybuf.b03 \
    vendor/sony/yoshino-common/proprietary/vendor/firmware/tzwvcpybuf.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/tzwvcpybuf.b04 \
    vendor/sony/yoshino-common/proprietary/vendor/firmware/tzwvcpybuf.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/tzwvcpybuf.b05 \
    vendor/sony/yoshino-common/proprietary/vendor/firmware/tzwvcpybuf.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/tzwvcpybuf.b06 \
    vendor/sony/yoshino-common/proprietary/vendor/firmware/tzwvcpybuf.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/tzwvcpybuf.b07 \
    vendor/sony/yoshino-common/proprietary/vendor/firmware/tzwvcpybuf.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/tzwvcpybuf.mdt \
    vendor/sony/yoshino-common/proprietary/vendor/radio/qcril_database/qcril.db:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/qcril.db \
    vendor/sony/yoshino-common/proprietary/vendor/radio/qcril_database/upgrade/0_initial.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/0_initial.sql \
    vendor/sony/yoshino-common/proprietary/vendor/radio/qcril_database/upgrade/10_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/10_version_update_ecc_table.sql \
    vendor/sony/yoshino-common/proprietary/vendor/radio/qcril_database/upgrade/1_version_intro.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/1_version_intro.sql \
    vendor/sony/yoshino-common/proprietary/vendor/radio/qcril_database/upgrade/2_version_add_wps_config.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/2_version_add_wps_config.sql \
    vendor/sony/yoshino-common/proprietary/vendor/radio/qcril_database/upgrade/3_version_update_wps_config.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/3_version_update_wps_config.sql \
    vendor/sony/yoshino-common/proprietary/vendor/radio/qcril_database/upgrade/4_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/4_version_update_ecc_table.sql \
    vendor/sony/yoshino-common/proprietary/vendor/radio/qcril_database/upgrade/5_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/5_version_update_ecc_table.sql \
    vendor/sony/yoshino-common/proprietary/vendor/radio/qcril_database/upgrade/6_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/6_version_update_ecc_table.sql \
    vendor/sony/yoshino-common/proprietary/vendor/radio/qcril_database/upgrade/7_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/7_version_update_ecc_table.sql \
    vendor/sony/yoshino-common/proprietary/vendor/radio/qcril_database/upgrade/8_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/8_version_update_ecc_table.sql \
    vendor/sony/yoshino-common/proprietary/vendor/radio/qcril_database/upgrade/9_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/9_version_update_ecc_table.sql \
    vendor/sony/yoshino-common/proprietary/vendor/usr/keylayout/gpio-keys.kl:$(TARGET_COPY_OUT_VENDOR)/usr/keylayout/gpio-keys.kl

PRODUCT_PACKAGES += \
    eglSubDriverAndroid \
    libEGL_adreno \
    libGLESv1_CM_adreno \
    libGLESv2_adreno \
    libQTapGLES \
    libq3dtools_adreno \
    libq3dtools_esx \
    libC2D2 \
    libCB \
    libOpenCL \
    libQSEEComAPI \
    libRSDriver_adreno \
    libadreno_utils \
    libadsp_default_listener \
    libadsprpc \
    libbccQTI \
    libc2d30_bltlib \
    libdevice_security_vendor \
    libdiag \
    libdsutils \
    libfastcvopt \
    libgsl \
    libhdcprx_module \
    libhdcptx_module \
    libidd \
    libidl \
    liblights-core \
    libllvm-glnext \
    libllvm-qcom \
    libmdmdetect \
    libmiscta \
    libmmcamera_faceproc \
    libmmcamera_faceproc2 \
    liboemcrypto \
    libqcci_legacy \
    libqdi \
    libqdp \
    libqmi \
    libqmi_cci \
    libqmi_client_helper \
    libqmi_client_qmux \
    libqmi_common_so \
    libqmi_csi \
    libqmi_encdec \
    libqmi_legacy \
    libqmiservices \
    libqsocket \
    librs_adreno \
    librs_adreno_sha1 \
    libsensor1 \
    libstagefright_hdcp \
    libsuntory \
    libsys-utils \
    libthermalclient \
    libwvhidl \
    libwvtee \
    vendor.semc.hardware.light@1.0 \
    vendor.semc.system.idd@1.0 \
    vendor.somc.hardware.security.secd@1.0 \
    libexcal_ckb_service_plugin \
    libexcal_color_ctrl_plugin \
    libexcal_debug_display_plugin \
    libexcal_exposure_ctrl_plugin \
    libexcal_face_detector_plugin \
    libexcal_flicker_detector_plugin \
    libexcal_focus_stats_conv_plugin \
    libexcal_food_comp_plugin \
    libexcal_food_detector_plugin \
    libexcal_hal_ctrl_plugin \
    libexcal_hdr_plugin \
    libexcal_idt_ctrl_plugin \
    libexcal_image_conv_plugin \
    libexcal_iq_ctrl_plugin \
    libexcal_jpeg_enc_plugin \
    libexcal_lens_ctrl_plugin \
    libexcal_motion_detector_plugin \
    libexcal_motion_estimation_plugin \
    libexcal_multiframe_nr_plugin \
    libexcal_object_tracker_plugin \
    libexcal_prc_image_conv_plugin \
    libexcal_process_ctrl_plugin \
    libexcal_raw_proc_plugin \
    libexcal_req_ctrl_plugin \
    libexcal_scene_detector_plugin \
    libexcal_snapshot_ctrl_plugin \
    libexcal_splitter_plugin \
    libexcal_stream_ctrl_plugin \
    camera.msm8998 \
    camera.qcom \
    sound_trigger.primary.msm8998 \
    libOmxVideoDSMode \
    libOmxVpp \
    libacdb-fts \
    libacdbloader \
    libacdbrtac \
    libadiertac \
    libadsp_hvx_callback_skel \
    libadsp_hvx_stub \
    libaudcal \
    libaudio_log_utils \
    libaudioalsa \
    libcacao_common \
    libcacao_process_ctrl \
    libcameralight \
    libcammw \
    libcammw_util \
    libcdsprpc \
    libchromaflash \
    libdepthmapwrapper \
    libexcal_core \
    libexcal_pal \
    libexcal_system \
    libfastcrc \
    libfastcvadsp_stub \
    libfastrpc_utf_stub \
    libflash_pmic \
    libgpustats \
    libhal_dbg \
    libjpegdhw \
    libjpegdmahw \
    libjpegehw \
    libmm-qcamera \
    libmmcamera2_c2d_module \
    libmmcamera2_cpp_module \
    libmmcamera2_frame_algorithm \
    libmmcamera2_iface_modules \
    libmmcamera2_imglib_modules \
    libmmcamera2_is \
    libmmcamera2_isp_modules \
    libmmcamera2_mct \
    libmmcamera2_mct_shimlayer \
    libmmcamera2_pp_buf_mgr \
    libmmcamera2_pproc_modules \
    libmmcamera2_q3a_core \
    libmmcamera2_sensor_modules \
    libmmcamera2_stats_algorithm \
    libmmcamera2_stats_lib \
    libmmcamera2_stats_modules \
    libmmcamera_bokeh \
    libmmcamera_chromaflash_lib \
    libmmcamera_csidtg \
    libmmcamera_dbg \
    libmmcamera_depth_map \
    libmmcamera_dummyalgo \
    libmmcamera_eebinparse \
    libmmcamera_eeprom_util \
    libmmcamera_eztune_module \
    libmmcamera_facedetection_lib \
    libmmcamera_hdr_gb_lib \
    libmmcamera_hvx_add_constant \
    libmmcamera_hvx_grid_sum \
    libmmcamera_imglib \
    libmmcamera_imglib_faceproc_adspstub \
    libmmcamera_interface \
    libmmcamera_isp_abf48 \
    libmmcamera_isp_aec_bg_stats47 \
    libmmcamera_isp_bf_stats47 \
    libmmcamera_isp_bg_stats46 \
    libmmcamera_isp_bhist_stats44 \
    libmmcamera_isp_black_level48 \
    libmmcamera_isp_bpc48 \
    libmmcamera_isp_cac47 \
    libmmcamera_isp_chroma_enhan40 \
    libmmcamera_isp_chroma_suppress40 \
    libmmcamera_isp_clamp_encoder40 \
    libmmcamera_isp_clamp_video40 \
    libmmcamera_isp_clamp_viewfinder40 \
    libmmcamera_isp_color_correct46 \
    libmmcamera_isp_color_xform_encoder46 \
    libmmcamera_isp_color_xform_video46 \
    libmmcamera_isp_color_xform_viewfinder46 \
    libmmcamera_isp_cs_stats46 \
    libmmcamera_isp_demosaic48 \
    libmmcamera_isp_demux48 \
    libmmcamera_isp_fovcrop_encoder46 \
    libmmcamera_isp_fovcrop_video46 \
    libmmcamera_isp_fovcrop_viewfinder46 \
    libmmcamera_isp_gamma44 \
    libmmcamera_isp_gic48 \
    libmmcamera_isp_gtm46 \
    libmmcamera_isp_hdr48 \
    libmmcamera_isp_hdr_be_stats46 \
    libmmcamera_isp_hdr_bhist_stats44 \
    libmmcamera_isp_ihist_stats46 \
    libmmcamera_isp_linearization40 \
    libmmcamera_isp_ltm47 \
    libmmcamera_isp_luma_adaptation40 \
    libmmcamera_isp_mce40 \
    libmmcamera_isp_mesh_rolloff44 \
    libmmcamera_isp_pdaf48 \
    libmmcamera_isp_pedestal_correct46 \
    libmmcamera_isp_rs_stats46 \
    libmmcamera_isp_scaler_encoder46 \
    libmmcamera_isp_scaler_video46 \
    libmmcamera_isp_scaler_viewfinder46 \
    libmmcamera_isp_sce40 \
    libmmcamera_isp_snr47 \
    libmmcamera_isp_sub_module \
    libmmcamera_optizoom_lib \
    libmmcamera_paaf_lib \
    libmmcamera_pdaf \
    libmmcamera_pdafcamif \
    libmmcamera_ppbase_module \
    libmmcamera_ppeiscore \
    libmmcamera_stillmore_lib \
    libmmcamera_sw2d_lib \
    libmmcamera_thread_services \
    libmmcamera_tintless_algo \
    libmmcamera_tintless_bg_pca_algo \
    libmmcamera_tuning \
    libmmcamera_tuning_lookup \
    libmmjpeg \
    libmmjpeg_interface \
    libmmlib2d_interface \
    libmmosal_proprietary \
    libmmqjpeg_codec \
    libmmqjpegdma \
    libmmsw_detail_enhancement \
    libmmsw_math \
    libmmsw_opencl \
    libmmsw_platform \
    liboptizoom \
    libqomx_core \
    libqomx_jpegdec \
    libqomx_jpegenc \
    libqomx_jpegenc_pipe \
    librebuffering \
    libseemore \
    libsmwrapper \
    libsomc_alfort \
    libsomc_alfortlp \
    libsomc_alfortlpserv \
    libsomc_alfortrsc \
    libsomc_bordeaux \
    libsomc_bordeauxrsc \
    libsomc_buttercake \
    libsomc_buttercakersc \
    libsomc_canele \
    libsomc_canelersc \
    libsomc_cheesescone \
    libsomc_cheesesconersc \
    libsomc_chokoballcmn \
    libsomc_chokoballpal \
    libsomc_dars \
    libsomc_darsrsc \
    libsomc_marble \
    libsomc_marblersc \
    libsomc_melonpan \
    libsomc_melonpanrsc \
    libsomc_mugichoco \
    libsomc_mugichocorsc \
    libsomc_pretzchoco \
    libsomc_pretzchocorsc \
    libsomc_raisin \
    libsomc_raisinrsc \
    libsomc_shortcake \
    libsomc_shortcakersc \
    libsomc_spica \
    libsomc_spicarsc \
    libsomc_sumomo \
    libsomc_sumomolp \
    libsomc_sumomolpserv \
    libsomc_sumomorsc \
    libsomc_toppo \
    libsomc_topporsc \
    libsomc_yummy \
    libsomc_yummyrsc \
    libsony_fooddetect \
    libsony_naruto \
    libvideobokeh \
    libvpphvx \
    libvpplibrary \
    libvqzip \
    libwfdcommonutils_proprietary \
    libwfdmmservice \
    libznr \
    libznrwrapper \
    vendor.somc.camera.device@3.2-impl \
    vendor.somc.camera.device@3.3-impl \
    vendor.somc.camera.device@3.4-impl \
    vendor.somc.hardware.camera.cacao@1.0 \
    vendor.somc.hardware.camera.cacao@2.0 \
    vendor.somc.hardware.camera.cacao@3.0-impl \
    vendor.somc.hardware.camera.cacao@3.0 \
    vendor.somc.hardware.camera.cacao@3.1 \
    vendor.somc.hardware.camera.device@1.0 \
    vendor.somc.hardware.camera.provider@1.0 \
    com.fingerprints.extension@1.0 \
    com.qualcomm.qti.ant@1.0 \
    com.qualcomm.qti.dpm.api@1.0_vendor \
    com.qualcomm.qti.imscmservice@2.0 \
    com.qualcomm.qti.imscmservice@2.1 \
    com.qualcomm.qti.imscmservice@2.2 \
    com.qualcomm.qti.uceservice@2.0 \
    com.qualcomm.qti.uceservice@2.1 \
    com.qualcomm.qti.uceservice@2.2 \
    com.qualcomm.qti.uceservice@2.3 \
    android.hardware.bluetooth@1.0-impl-qti \
    android.hardware.gatekeeper@1.0-impl-qti \
    android.hardware.gnss@2.0-impl-qti \
    android.hardware.keymaster@3.0-impl-qti \
    vendor.qti.gnss@3.0-impl \
    vendor.qti.hardware.fm@1.0-impl \
    vendor.qti.hardware.qteeconnector@1.0-impl \
    vulkan.msm8998 \
    lib-imsSDP \
    lib-imscmservice \
    lib-imsdpl \
    lib-imsqimf \
    lib-imsrcs-v2 \
    lib-imsrcsbaseimpl \
    lib-imsvtcore \
    lib-imsxml \
    lib-rcsconfig \
    lib-rtpcommon \
    lib-rtpcore \
    lib-rtpsl \
    lib-siputility \
    lib-uceservice \
    libFIDOKeyProvisioning \
    libFidoCrypto_vendor \
    libGPreqcancel \
    libGPreqcancel_svc \
    libMiscTAApi.sony \
    libMiscTaWrapper \
    libQTEEConnector_vendor \
    libSecureUILib \
    libStDrvInt \
    libbatching \
    libbtnv \
    libcne \
    libcneapiclient \
    libcneoplookup \
    libconfigdb \
    libdataitems \
    libdisp-aba \
    libdpmqmihal \
    libdrmfs \
    libdrmtime \
    libdsi_netctrl \
    libgdtap \
    libgeofencing \
    libgnss \
    libgps.utils \
    libhdr_tm \
    libizat_client_api \
    libizat_core \
    libkeymasterdeviceutils \
    libkeymasterprovision \
    libkeymasterutils \
    liblbs_core \
    libloc_api_v02 \
    libloc_core \
    liblocation_api \
    liblocationservice \
    liblocationservice_glue \
    liblowi_client \
    liblqe \
    libnetmgr \
    libnetmgr_common \
    libnetmgr_nr_fusion \
    libnetmgr_rmnet_ext \
    libnlnetmgr \
    libpdmapper \
    libpdnotifier \
    libperipheral_client \
    libpn553_fw \
    libprotobuf-c-idd \
    libqcmaputils \
    libqcrilFramework \
    libqcrildatactl \
    libqdma_file_agent \
    libqisl \
    libqrtr \
    libqseed3 \
    librcc \
    libril-qc-hal-qmi \
    libril-qc-logger \
    libril-qc-ltedirectdisc \
    libril-qc-radioconfig \
    libril-qcril-hook-oem \
    librilqmiservices \
    librpmb \
    libsdm-color \
    libsdm-diag \
    libsdm-disp-vndapis \
    libsdmcore \
    libsdmextension \
    libsdmutils \
    libsdsprpc \
    libsecureui \
    libsecureui_svcsock \
    libsensor_reg \
    libsettings \
    libsns_low_lat_stream_stub \
    libsomcqnswrapper \
    libssd \
    libsystem_health_mon \
    libta \
    libthermalioctl \
    libtime_genoff \
    libtinyxml2_1 \
    libtpm \
    libwms \
    libwqe \
    libxml \
    libxtadapter \
    qcrild_librilutils \
    qtibus \
    qtimutex \
    sensor_calibrate \
    sensors.finger-pickup \
    sensors.ssc \
    vendor.display.color@1.0 \
    vendor.display.postproc@1.0 \
    vendor.qti.data.factory@2.0 \
    vendor.qti.data.factory@2.1 \
    vendor.qti.data.factory@2.2 \
    vendor.qti.data.factory@2.3 \
    vendor.qti.data.mwqem@1.0 \
    vendor.qti.data.slm@1.0 \
    vendor.qti.gnss@1.0 \
    vendor.qti.gnss@1.1 \
    vendor.qti.gnss@1.2 \
    vendor.qti.gnss@2.0 \
    vendor.qti.gnss@2.1 \
    vendor.qti.gnss@3.0 \
    vendor.qti.hardware.bluetooth_sar@1.0 \
    vendor.qti.hardware.data.cne.internal.api@1.0 \
    vendor.qti.hardware.data.cne.internal.constants@1.0 \
    vendor.qti.hardware.data.cne.internal.server@1.0 \
    vendor.qti.hardware.data.connection@1.0 \
    vendor.qti.hardware.data.connection@1.1 \
    vendor.qti.hardware.data.dynamicdds@1.0 \
    vendor.qti.hardware.data.iwlan@1.0 \
    vendor.qti.hardware.data.latency@1.0 \
    vendor.qti.hardware.data.lce@1.0 \
    vendor.qti.hardware.data.qmi@1.0 \
    vendor.qti.hardware.fm@1.0_vendor \
    vendor.qti.hardware.mwqemadapter@1.0 \
    vendor.qti.hardware.qteeconnector@1.0 \
    vendor.qti.hardware.radio.am@1.0 \
    vendor.qti.hardware.radio.ims@1.0 \
    vendor.qti.hardware.radio.ims@1.1 \
    vendor.qti.hardware.radio.ims@1.2 \
    vendor.qti.hardware.radio.ims@1.3 \
    vendor.qti.hardware.radio.ims@1.4 \
    vendor.qti.hardware.radio.ims@1.5 \
    vendor.qti.hardware.radio.ims@1.6 \
    vendor.qti.hardware.radio.ims@1.7 \
    vendor.qti.hardware.radio.internal.deviceinfo@1.0 \
    vendor.qti.hardware.radio.lpa@1.0 \
    vendor.qti.hardware.radio.lpa@1.1 \
    vendor.qti.hardware.radio.qcrilhook@1.0 \
    vendor.qti.hardware.radio.qtiradio@1.0 \
    vendor.qti.hardware.radio.qtiradio@2.0 \
    vendor.qti.hardware.radio.qtiradio@2.1 \
    vendor.qti.hardware.radio.qtiradio@2.2 \
    vendor.qti.hardware.radio.qtiradio@2.3 \
    vendor.qti.hardware.radio.qtiradio@2.4 \
    vendor.qti.hardware.radio.uim@1.0 \
    vendor.qti.hardware.radio.uim@1.1 \
    vendor.qti.hardware.radio.uim@1.2 \
    vendor.qti.hardware.radio.uim_remote_client@1.0 \
    vendor.qti.hardware.radio.uim_remote_client@1.1 \
    vendor.qti.hardware.radio.uim_remote_client@1.2 \
    vendor.qti.hardware.radio.uim_remote_server@1.0 \
    vendor.qti.hardware.slmadapter@1.0 \
    vendor.qti.hardware.tui_comm@1.0 \
    vendor.qti.ims.callcapability@1.0 \
    vendor.qti.ims.callinfo@1.0 \
    vendor.qti.ims.factory@1.0 \
    vendor.qti.ims.factory@1.1 \
    vendor.qti.ims.rcsconfig@1.0 \
    vendor.qti.ims.rcsconfig@1.1 \
    vendor.qti.ims.rcsconfig@2.0 \
    vendor.qti.ims.rcsconfig@2.1 \
    vendor.qti.imsrtpservice@3.0-service-Impl \
    vendor.qti.imsrtpservice@3.0_vendor \
    vendor.qti.latency@2.0 \
    vendor.qti.latency@2.1 \
    vendor.somc.hardware.miscta@1.0 \
    libFastRPC_AUE_Forward_skel \
    libFastRPC_UTF_Forward_Qtc2_skel \
    libFastRPC_UTF_Forward_skel \
    libadsp_fd_skel \
    libadsp_hvx_add_constant \
    libadsp_hvx_skel \
    libapps_mem_heap \
    libdspCV_skel \
    libfastcvadsp \
    libfastcvadsp_skel \
    libscveBlobDescriptor_skel \
    libscveObjectSegmentation_skel \
    libscveT2T_skel \
    libsns_low_lat_stream_skel \
    libsomc_alfortlpserv_skel \
    libsomc_sumomolpserv_skel \
    libvpp_frc \
    libvpp_svc_skel \
    com.qualcomm.qti.dpm.api@1.0 \
    fm_helium \
    lib-imscamera \
    lib-imsvideocodec \
    lib-imsvt \
    lib-imsvtextutils \
    lib-imsvtutils \
    libdiag_system \
    libdpmctmgr \
    libdpmfdmgr \
    libdpmframework \
    libdpmtcm \
    libfm-hci \
    libimscamera_jni \
    libimsmedia_jni \
    libmwqemiptablemgr \
    vendor.qti.diaghal@1.0 \
    vendor.qti.hardware.fm@1.0 \
    vendor.qti.imsrtpservice@3.0 \
    CneApp \
    IWlanService \
    TimeService \
    QtiTelephonyService \
    dpmserviceapp \
    ims \
    qcrilmsgtunnel \
    com.qti.dpmframework \
    dpmapi \
    qcrilhook \
    android.hardware.gnss@2.0-service-qti.xml \
    vendor.qti.gnss@3.0-service.xml \
    adpl \
    adsprpcd \
    cnd \
    cnss-daemon \
    dpmQmiMgr \
    hvdcp_opti \
    android.hardware.bluetooth@1.0-service-qti \
    android.hardware.drm@1.1-service.widevine \
    android.hardware.gatekeeper@1.0-service-qti \
    android.hardware.gnss@2.0-service-qti \
    android.hardware.keymaster@3.0-service-qti \
    qcrild \
    vendor.display.color@1.0-service \
    vendor.qti.hardware.qteeconnector@1.0-service \
    vendor.qti.hardware.tui_comm@1.0-service-qti \
    vendor.semc.hardware.secd@1.0-service \
    vendor.semc.system.idd@1.0-service \
    vendor.somc.hardware.camera.provider@1.0-service \
    vendor.somc.hardware.miscta@1.0-service \
    idd-logreader \
    iddd \
    ims_rtp_daemon \
    imsdatadaemon \
    imsqmidaemon \
    imsrcsd \
    irsc_util \
    keyprovd \
    loc_launcher \
    lowi-server \
    mlid \
    mlog_qmi_service \
    mm-pp-dpps \
    msm_irqbalance \
    netmgrd \
    pd-mapper \
    pm-proxy \
    pm-service \
    port-bridge \
    qns \
    qrtr-cfg \
    qrtr-lookup \
    qrtr-ns \
    qseecomd \
    qti \
    rmt_storage \
    sct_service \
    sensors.qti \
    slim_daemon \
    sony-modem-switcher \
    ta_qmi_service \
    tad \
    tftp_server \
    thermal-engine \
    time_daemon \
    wvkbd \
    xtra-daemon \
    xtwifi-client \
    xtwifi-inet-agent \
    dpmd

PRODUCT_PACKAGES += \
    system_ext_priv-app_ims_lib_arm64_libimscamera_jni_so \
    system_ext_priv-app_ims_lib_arm64_libimsmedia_jni_so \
    vendor_lib_libEGL_adreno_so \
    vendor_lib_libGLESv2_adreno_so \
    vendor_lib_libq3dtools_adreno_so \
    vendor_lib64_libEGL_adreno_so \
    vendor_lib64_libGLESv2_adreno_so \
    vendor_lib64_libq3dtools_adreno_so \
    vendor_lib64_android_hardware_keymaster@3_0-impl-qti_so
